#!/bin/bash
#
# test simple command /bin/ls

command="history"


# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c ":"`
if [ $nmatch -ge 1 ]; then
	  print_ko
	  echo "Pogrammers need help: implement help!"
else
	   print_ok
fi

# clean up
stop_shell
rm -f $tmp_file
