#!/bin/bash
#
# check if a medium size command line does not break the shell
# This will put an incorrect command into sh to compare
# This will also check your line count. Ask if you have questions.
# Tahlia and Lance were here

command="
jd"
tmp_file1="checker_tmp_badf_$RANDOM"
tmp_file2="checker_tmp_badf_$RANDOM"
tmp_directory="newdirectorywithaname"


# clean up
stop_shell
rm -f $tmp_file
rm -f $tmp_file1
rm -f $tmp_file2

# create a pseudo random file
#ouch $tmp_file
# send commands
mkdir $tmp_directory
cp $PWD/$SHELL $tmp_directory/newtest
echo "$command" | $PWD/$tmp_directory/newtest > $tmp_file1 2> $tmp_file1
rm $tmp_directory/newtest
cp /bin/sh $tmp_directory/newtest
echo "$command" | $PWD/$tmp_directory/newtest > $tmp_file2 2> $tmp_file2

# wait a little bit
$SLEEP $SLEEPSECONDS
#echo $tmp_file1
#echo $tmp_file2
# check the result
nmatch=`cat $tmp_file1 | grep -c $tmp_file2`
#echo $nmatch
if cmp -s "$tmp_file1" "$tmp_file2"; then
    nmatch=1
else
    nmatch=0
fi
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
rm -f $tmp_file1
rm -f $tmp_file2
rm -rf $tmp_directory
