#!/bin/bash
#
# test simple the apperance of error message on wrong messages

command="/bin/ls"

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | wc -l`
if [ $nmatch -eq 0 ]; then
	   print_ko
           echo "Proper error message not being printed"
else
	   print_ok
fi

# clean up
stop_shell
rm -f $tmp_file
