#!/bin/bash
#
# test simple command /bin/ls

command="
"

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "fault\|:\|seg:\|not"`
if [ $nmatch -ge 1 ]; then
	   print_ko
	   echo "Handle new line inputs";
else
	   print_ok
fi

# clean up
stop_shell
rm -f $tmp_file
