#!/bin/bash
#
# check if the getline function was used by using ltrace

command="exit 90"

# clean up
stop_shell

# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`echo $?`
if [ $nmatch -eq 90 ]; then
    print_ok
else
    print_ko
    echo "Handle exit status\n"
fi

# clean up
stop_shell
rm -f $tmp_file
