#!/bin/bash
#
# Can you write and overwrite multiple aliases?

command="alias Kappa=b
alias a=b
alias Kappa=kapppa
alias Kappa=kapppa
alias a=c
alias a=kapppa
alias a=d
alias b=kapppa
alias"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep kapppa | wc -l`

if [ $nmatch -eq 2 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
