#!/bin/bash
#
# run ls with arguments

tmp_file=".checker_tmp_file_$RANDOM"
command="/bin/ls -l -a"

# clean up
stop_shell
rm -f $tmp_filepath

# create a pseudo random file
touch $tmp_file
chmod 761 $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat "$OUTPUTFILE" | grep "$tmp_file" | grep -c "rwxrw---x"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_filepath
