#!/bin/bash
#
# test simple command /bin/ls

command="/bin/ls"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
mkdir tmp_10345 && chdir tmp_10345 && touch $tmp_file && cd ..
echo $(pwd)/tmp_1035/$tmp_file > $full_path
echo $(pwd)/tmp_1035 > $dir_path
# run command
echo "cd tmp_10345" | $SHELL
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "$tmp_file"`
if [ $nmatch -eq 1 ]; then
	   print_ok
else
	   print_ko
	   echo "change directory doesn't work"
fi

# clean up
stop_shell
rm -f $full_path
rm -f -r $dir_path
