#!/bin/bash
#
# test the style of  all the c programs
# doesn't indicate where the problem is happening
# This check assums betty is installed on your machine

command="betty"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# run command
$command *.c > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c 'ERROR\|WARNING'`
if [ $nmatch -eq 0 ]; then
	print_ok
else
	print_ko
	echo "Fix $nmatch errors"
fi

# clean up
stop_shell
rm -f $tmp_file
