#!/bin/bash
#
# test simple command /bin/ls

command=""

# clean up
stop_shell

# create a pseudo random file
touch $tmp_file
# run command
echo "$command" | $SHELL 2> $OUTPUTFILE > /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "Aborted"`
n2=`cat $OUTPUTFILE | grep -c "fault"`
n3=$nmatch||$n2
if [ $n3 -eq 0 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
