#!/bin/bash
#
# test simple command usr/bin/printenv

command="/usr/bin/printenv"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
echo "$command" | /bin/sh > $tmp_file
# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
cmp -s "$OUTPUTFILE" "$tmp_file"
if [ `echo $?` -eq 0 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
