#!/bin/bash
#
# test simple non command, only spaces

command="                                                           "
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> $ERROROUTPUTFILE &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
if [ ! -s $OUTPUTFILE ]; then
    if [ ! -s $ERROROUTPUTFILE ]; then
	print_ok
    fi
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
