#!/bin/bash
#
# Can you correctly ignore impossible path characters?

command="echo $PATH.
echo $PATH,
echo $PATH_
echo $PATH%
echo $PATH.
echo $PATH@
echo $PATH!
echo $PATH~
echo $PATH#
echo $PATH?
echo $PATH:"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | sh > $tmp_file 2> /dev/null &
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | wc -m`
nmatch2=`cat $tmp_file | wc -m`
if [ $nmatch -eq $nmatch2 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
