#!/bin/bash
#
# test simple command /bin/ls&&/bin/ls

command="alias ml=ls"

# run command
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c ":"`
if [ $nmatch -eq 1 ]; then
	   print_ko
	   echo "Handle aliases like alias ml=ls"
else
	   print_ok
fi

# clean up
stop_shell
rm -f $tmp_file
