#!/bin/bash
#
# makes sure the exit builting command is implemented

command="set"


# send commands
echo "$command" | $SHELL >& $OUTPUTFILE

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE|grep -c "no"` #we don't take no for an anwer
if [ $nmatch -ge 1 ]; then
	   print_ko
	   echo "Implement a built in set function"
else
	   print_ok
fi

# clean up
stop_shell
