#!/bin/bash
#
# Can you set and overwrite env?

command="setenv Kappa hi
setenv Kappa hello
setenv Kappa kapppa
env"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep Kappa=kapppa | wc -l`
nmatch2=`cat $OUTPUTFILE | grep Kappa= | wc -l`
if [ $nmatch -eq 1 ] && [ $nmatch2 -eq 1 ]; then
	   print_ok
else
	   print_ko
fi

# clean up
stop_shell
rm -f $tmp_file
