#!/usr/bin/expect -f

set timeout -1

# this doesn't behave the way I'd like
# set command [lindex $argv 0]
# if {[llength $argv] == 0} {
#  send_user "Usage: scriptname command\n"
#  exit 1
# }
set command "cd .."
# just using pwd to confirm
set command2 "pwd"

spawn /bin/sh 
match_max 100000
expect -re {\$ $}
send -- "$command\r"
expect -re {\$ $}
send -- "$command2\r"
expect -re {^[^\n]+\n(.*)\r\n\$ $}
set baseout $expect_out(1,string)
send -- "exit\r"
expect eof

spawn ./simple_shell
match_max 100000
expect -exact " (\$) "
send -- "$command\r"
expect -exact " (\$) "
send -- "$command2\r"
expect -re {^[^\n]+\n(.*)\r\n \(\$\) $}
set testout $expect_out(1,string)
send -- "exit\r"
expect eof

if { $baseout != $testout } {
puts "\nFail!\n";
} else {
puts "\nSuccess!\n"; 
}
