#!/bin/bash
#
# test the existance of  README.md

command="/bin/ls"

echo "$command" | $SHELL > $OUTPUTFILE 2> /dev/null &

# wait a little bit
$SLEEP $SLEEPSECONDS

# check the result
nmatch=`cat $OUTPUTFILE | grep -c "README.md"`
if [ $nmatch -eq 1 ]; then
	size=`du README.md|cut -f1`
	if [ $size -eq 0 ]; then
		print_ko
		echo "README is empty"
	else
	   print_ok
	fi
else
	   print_ko
	   echo "Write the README"
fi

# clean up
stop_shell
rm -f $tmp_file
