#!/bin/bash
#
# check that exit can take arguments as exit codes

command="exit 98"
tmp_file="checker_tmp_file_$RANDOM"

# clean up
stop_shell
rm -f $tmp_file

# create a pseudo random file
touch $tmp_file
# send commands
$ECHO "$command" | $SHELL 2> /dev/null
$ECHO "$?" > $OUTPUTFILE 2> /dev/null
# wait a little
$SLEEP $SLEEPSECONDS

# check the result
res=`$CAT "$OUTPUTFILE"`
if [ "$res" == "98" ]; then
    print_ok
else
    print_ko
fi

# clean up
stop_shell
$RM -f $tmp_file
